---
title: "Checkliste"
output: webex::webex_default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!requireNamespace("webex")) {
  stop("You must have the 'webex' package installed to knit HTML from this template.\n   devtools::install_github(\"psyteachr/webex\")")
} else {
  library("webex")
}
library("kableExtra")
```

```{css, echo=FALSE}
.box {
        display: flex;
      }

      .box > * {
        flex: 1 1 0;
      }
```


```{css, echo=FALSE}
.flex { 
    display: flex; 
    justify-content: center; 
    align-items: center;
}
```

### Das kann ich jetzt:

```{r, echo=FALSE}
checkliste_tbl <- data.frame(
  "Thema" = c("Terme aufstellen", "", "Umgang mit Termen", "", "", "", "", "", "", "", "", "Dreieck", "", "", "", "Trapez", "", "", "", "Parallelogramm", "", "", "","Vieleck","", "Kreis", "", "", "", ""),
  
  "Ich kann" = c("... Terme mit mehreren Variablen aufstellen","", "... gleichartige Terme zusammenfassen", "... Plus- und Minusklammern in Termen auflösen", "... Terme mit Zahlen multiplizieren und durch Zahlen dividieren", "... Terme mit Hilfe der Vorrangregeln vereinfachen", "... eine Klammer in Termen ausmultiplizieren", "... gemeinsame Faktoren aus Summen oder Differenzen ausklammern", "... zwei Klammern in Termen ausmultiplizieren", "... die binomischen Formeln anwenden.", "", "... den Flächeninhaltes eines Dreiecks berechnen", "... die Grundseite eines Dreiecks berechnen, wenn der Flächeninhalt und die Höhe gegeben sind.", "... die Höhe eines Dreiecks berechnen, wenn der Flächeninhalt und die Grundseite gegeben sind.", "", "... den Flächeninhalt eines Trapezes berechnen.", "... die Höhe eines Trapezes berechnen, wenn der Flächeninhalt und die Längen der beiden parallelen Seiten gegeben sind.", "... die Länge einer der parallelen Seiten eines Trapezes berechnen, wenn der Flächeninhalt und die Höhe gegeben sind.", "", "... den Flächeninhalt eines Parallelogramms berechnen.", "... die Grundseite eines Parallelogramms berechnen, wenn der Flächeninhalt und die Höhe gegeben sind.", "... die Höhe eines Parallelogramms berechnen, wenn der Flächeninhalt und die Grundseite gegeben sind.", "", "Flächeninhalte zusammengesetzter Figuren berechnen", "", " ... den Flächeninhalt eines Kreises berechnen.", "... den Umfang eines Kreises berechnen.", ".. den Radius/Durchmesser eines Kreises berechnen, wenn der Flächeninhalt des Kreises gegeben ist.", "... den Radius/Durchmesser eines Kreises berechnen, wenn der Umfang des Kreises gegeben ist. ", " ... den Radius eines Kreises berechnen, wenn der Durchmesser des Kreises gegeben ist und umgekehrt."),
  
  "Hilfe" = c("hier", "", "hier", "hier", "hier", "hier", "hier", "hier", "hier", "hier", "", "[hier]((https://gdischinger.github.io/Mathe_8d/03FormelnErstellen/Dreieck.html))", "hier", "hier", "", "hier", "hier", "hier", "", "hier", "hier", "hier", "", "hier", "", "hier", "hier", "hier", "hier", "hier"
    ),
  
  "Aufgaben" = c("Aufgaben", "", "Aufgaben", "Aufgaben", "Aufgaben", "Aufgaben", "Aufgaben", "Aufgaben", "Aufgaben", "Aufgaben", "", "Aufgaben", "Aufgaben", "Aufgaben", "", "Aufgaben", "Aufgaben", "Aufgaben", "", "Aufgaben", "Aufgaben", "Aufgaben", "", "Aufgaben", "", "Aufgaben", "Aufgaben", "Aufgaben", "Aufgaben", "Aufgaben"
    )
)

checkliste_tbl %>%
  kbl(col.names = c("Thema", "Ich kann...", "Hilfe findest du", "Aufgaben")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive",full_width = F, position = "left"))%>%
  column_spec(1, border_right = T) %>%
  column_spec(2, width = "35em", border_right = T) %>%
  column_spec(3, border_right = T) %>%
  column_spec(4) 


# kbl(checkliste_tbl, col.names = c("Ich kann...", "Hilfe", "Aufgaben")) %>%
#   # kable_paper(full_width = F) %>%
#   column_spec(1, background = "yellow", border_right = T) %>%
#   column_spec(2, border_right = T) %>%
#   column_spec(3, border_right = T) %>%
#   kable_styling()

```


<!-- ```{r, 'kable'} -->
<!-- ``` -->
<!-- <br> |Ich kann... | Hilfe | Aufgaben -->
<!-- ------|------|------|----- -->
<!-- $\checkmark$ | ... die binomischen Formeln anwenden. | hier | Aufgaben -->
<!-- <br>   |               **Dreieck**              |      **Dreieck**       |**Dreieck** -->
<!-- $\checkmark$ | ... den Flächeninhaltes eines Dreiecks berechnen | hier | Aufgaben -->
<!-- $\checkmark$ | ... die Grundseite eines Dreiecks berechnen, wenn der Flächeninhalt und die Höhe gegeben sind. | hier | Aufgaben -->
<!-- $\checkmark$ |... die Höhe eines Dreiecks berechnen, wenn der Flächeninhalt und die Grundseite gegeben sind. | hier | Aufgaben -->
<!-- <br>   |        **Trapez**                              |    **Trapez**            |**Trapez**  -->
<!-- $\checkmark$ | ... den Flächeninhalt eines Trapezes berechnen | hier | Aufgaben -->
<!-- $\checkmark$ | ... die Höhe eines Trapezes berechnen, wenn der Flächeninhalt und die Längen der beiden parallelen Seiten gegeben sind. | hier | Aufgaben -->
<!-- $\checkmark$ | ... die Länge einer der parallelen Seiten eines Trapezes berechnen, wenn der Flächeninhalt und die Höhe gegeben sind. | hier | Aufgaben -->
<!-- <br>  |        **Parallelogramm**                              | **Parallelogramm**               |**Parallelogramm** -->
<!-- $\checkmark$ | ... den Flächeninhalt eines Parallelogramms berechnen. | hier | Aufgaben -->
<!-- $\checkmark$ | ... die Grundseite eines Parallelogramms berechnen, wenn der Flächeninhalt und die Höhe gegeben sind. | Schalg nach! | Aufgaben -->
<!-- $\checkmark$ | ... die Höhe eines Parallelogramms berechnen, wenn der Flächeninhalt und die Grundseite gegeben sind. | hier | Aufgaben -->
<!-- <br>        |               **Kreis**                           |   **Kreis**          |**Kreis** -->
<!-- $\checkmark$ | ... den Flächeninhalt eines Kreises berechnen. | hier | Aufgaben -->
<!-- $\checkmark$ | ... den Umfang eines Kreises berechnen. | hier | Aufgaben -->
<!-- $\checkmark$ | ... den Radius/Durchmesser eines Kreises berechnen, wenn der Flächeninhalt des Kreises gegeben ist. | hier | Aufgaben -->
<!-- $\checkmark$ | ... den Radius/Durchmesser eines Kreises berechnen, wenn der Umfang des Kreises gegeben ist. | hier | Aufgaben -->
<!-- $\checkmark$ | ... den Radius eines Kreises berechnen, wenn der Durchmesser des Kreises gegeben ist und umgekehrt. | hier | Aufgaben -->